name: Deployment

on:
  release:
    types: [created]

jobs:
  distribute_binaries:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [arm64, x86_64]
    steps:
      - name: Configure Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Cache SPM dependencies
        uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Compile ${{ matrix.platform }} Binary
        run: |
          swift build -c release --arch ${{ matrix.platform }}
          zip -j file-organiser-${{ matrix.platform }}.zip .build/${{ matrix.platform }}-apple-macosx/release/file-organiser
      - name: Upload ${{ matrix.platform }} Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: file-organiser-${{ matrix.platform }}.zip
          asset_name: file-organiser-${{ matrix.platform }}.zip
          asset_content_type: application/zip
